services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  express-server-app:
    build:
      context: ./express-server-app
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./express-server-app/src:/usr/src/app/src